### ISSUE TITLE
There are currently no examples for usage

### ISSUE THREAD

**Issue by bwasilewski** [Subzero-ftspdev/VideoConvertJs#2]
**Is your feature request related to a problem? Please describe.**
There are no examples on the readme describing how to use the project.

**Describe the solution you'd like**
A short example of how to run this script added to the README file.

**Comment by Subzero-ftspdev** [comment]
HI @bwasilewski 

Thanks for pointing this out 🥇 

If you would like to submit a pull request with the example(s) I'd be happy to merge it 👍

**Comment by Subzero-ftspdev** [comment]
Issue closed 

https://github.com/Subzero-ftspdev/VideoConvertJs/pull/3
